# Generated by Django 4.0.4 on 2022-04-25 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worldtravelerapp', '0002_alter_travellist_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('svg', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='travellist',
            name='creator',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travellist',
            name='countrys',
            field=models.ManyToManyField(to='worldtravelerapp.country'),
        ),
    ]
