# Generated by Django 4.0.4 on 2022-04-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelerapp', '0004_alter_country_name_alter_travellist_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellist',
            name='countrys',
            field=models.ManyToManyField(default=None, to='worldtravelerapp.country'),
        ),
    ]
