# Generated by Django 4.0.4 on 2022-04-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelerapp', '0006_alter_travellist_countrys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellist',
            name='countrys',
            field=models.ManyToManyField(blank=True, to='worldtravelerapp.country'),
        ),
    ]
