# Generated by Django 4.0.4 on 2022-04-27 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worldtravelerapp', '0008_alter_travellist_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellist',
            name='countrys',
            field=models.ManyToManyField(blank=True, related_name='travellist', to='worldtravelerapp.country'),
        ),
        migrations.AlterField(
            model_name='travellist',
            name='creator',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travellistid', to=settings.AUTH_USER_MODEL),
        ),
    ]
